# netlify.toml
[build]
  publish = "app/.next"
  command = "cd app && npm install --legacy-peer-deps && npx prisma generate && npm run build"
  environment = { NODE_VERSION = "20" }

# Настройки для Next.js на Netlify с серверными функциями
[functions]
  directory = "app/.next/server/pages/api"

# Редирект apex -> www (на стороне Netlify)  
[[redirects]]
  from = "https://upak.space/*"
  to   = "https://www.upak.space/:splat"
  status = 301
  force  = true

# API роуты - редирект на backend (для production)
[[redirects]]
  from = "/api/orders"
  to   = "https://upak.tech:8001/api/orders"
  status = 200
  force = false

[[redirects]]
  from = "/api/orders/*"
  to   = "https://upak.tech:8001/api/orders/:splat" 
  status = 200
  force = false

# SPA-фолбэк для клиентской маршрутизации
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Заголовки для статических ресурсов
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Заголовки безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"